using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using UnityEditor;
using UnityEngine;

namespace BitFoxDen
{
    /// <summary>
    /// Unity Rewinder - A simple vertical timeline for local Git commits.
    /// Place this script inside an "Editor" folder in your Unity project.
    /// </summary>
    public class UnityRewinder : EditorWindow
    {
        // Struct to hold our commit information
        private struct CommitData
        {
            public string Hash;
            public string Message;
            public string Time;
        }

        private readonly List<CommitData> _commits = new();
        private Vector2 _scrollPosition;
        private int _selectedIndex = -1;
        private string _activeHash = "";
        private bool _isGitInitialized;
        private string _gitError = "";
        private bool _isProcessing;
        private string _workingDirectory = "";

        private const string GITIGNORE_CONTENT = @"# This .gitignore file should be placed at the root of your Unity project directory
#
# Get latest from https://github.com/github/gitignore/blob/main/Unity.gitignore
#
# Recommended: add any editor/OS/tool-specific ignore rules from the Global/ templates as needed.
# See: https://github.com/github/gitignore/tree/main/Global
#
.utmp/
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/
*.log

# By default unity supports Blender asset imports, *.blend1 blender files do not need to be commited to version control.
*.blend1
*.blend1.meta

# MemoryCaptures can get excessive in size.
# They also could contain extremely sensitive data
/[Mm]emoryCaptures/

# Recordings can get excessive in size
/[Rr]ecordings/

# Uncomment this line if you wish to ignore the asset store tools plugin
# /[Aa]ssets/AssetStoreTools*

# Autogenerated Jetbrains Rider plugin
/[Aa]ssets/Plugins/Editor/JetBrains*
# Jetbrains Rider personal-layer settings
*.DotSettings.user

# Visual Studio cache directory
.vs/

# Gradle cache directory
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.slnx
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Mono auto generated files
mono_crash.*

# Builds
*.apk
*.aab
*.unitypackage
*.unitypackage.meta
*.app

# Crashlytics generated file
crashlytics-build.properties

# TestRunner generated files
InitTestScene*.unity*

# Addressables default ignores, before user customizations
/ServerData
/[Aa]ssets/StreamingAssets/aa*
/[Aa]ssets/AddressableAssetsData/link.xml*
/[Aa]ssets/Addressables_Temp*
# By default, Addressables content builds will generate addressables_content_state.bin
# files in platform-specific subfolders, for example:
# /Assets/AddressableAssetsData/OSX/addressables_content_state.bin
/[Aa]ssets/AddressableAssetsData/*/*.bin*

# Visual Scripting auto-generated files
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Flow/UnitOptions.db
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Flow/UnitOptions.db.meta
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Core/Property Providers
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Core/Property Providers.meta

# Auto-generated scenes by play mode tests
/[Aa]ssets/[Ii]nit[Tt]est[Ss]cene*.unity*

# Auto-generated cache in Assets folder
/[Aa]ssets/[Ss]ceneDependencyCache*";

        [MenuItem("Window/Unity Rewinder")]
        public static void ShowWindow()
        {
            // Open the window and set its title
            UnityRewinder window = GetWindow<UnityRewinder>("Unity Rewinder");
            window.minSize = new Vector2(300, 400);
            window.Show();
        }

        private void OnEnable()
        {
            _workingDirectory = Application.dataPath.Substring(0, Application.dataPath.LastIndexOf("/Assets", StringComparison.Ordinal));
            RefreshTimeline();
        }

        private void OnGUI()
        {
            if (!_isGitInitialized)
            {
                DrawUninitializedState();
                return;
            }

            DrawTopBar();
            DrawTimeline();
            DrawBottomBar();
        }

        /// <summary>
        /// Renders the UI when no Git repository is found.
        /// </summary>
        private void DrawUninitializedState()
        {
            GUILayout.Space(20);
            GUILayout.Label("Unity Rewinder", EditorStyles.boldLabel);
            EditorGUILayout.HelpBox("No Git repository found in this Unity project.\nUnity Rewinder requires a local Git repository to function.",
                MessageType.Warning);
        
            if (!string.IsNullOrEmpty(_gitError))
            {
                EditorGUILayout.HelpBox(_gitError, MessageType.Error);
            }

            GUILayout.Space(10);
            if (GUILayout.Button("Initialize Local Git Repository", GUILayout.Height(30)))
            {
                RunGitCommand("init");
                EnsureGitIgnoreExists();
                try { RunGitCommand("checkout -b main"); } catch { }
                RefreshTimeline();
            }
        }

        /// <summary>
        /// Ensures that the Unity .gitignore file exists at the root of the project.
        /// </summary>
        private void EnsureGitIgnoreExists()
        {
            var gitIgnorePath = Path.Combine(_workingDirectory, ".gitignore");

            if (File.Exists(gitIgnorePath)) {
                return;
            }
            
            try
            {
                File.WriteAllText(gitIgnorePath, GITIGNORE_CONTENT);
                UnityEngine.Debug.Log("Unity Rewinder: Auto-created default Unity .gitignore file to prevent tracking unnecessary files.");
            }
            catch (Exception ex)
            {
                UnityEngine.Debug.LogError("Unity Rewinder: Failed to write .gitignore file: " + ex.Message);
            }
        }

        /// <summary>
        /// Draws the top bar with the "Create checkpoint" button.
        /// </summary>
        private void DrawTopBar()
        {
            GUILayout.Space(10);
        
            EditorGUI.BeginDisabledGroup(_isProcessing);
            if (GUILayout.Button("Create checkpoint", GUILayout.Height(35)))
            {
                CreateCheckpointAsync();
            }
            EditorGUI.EndDisabledGroup();
        
            GUILayout.Space(10);
        
            // Draw a separator line
            Rect rect = EditorGUILayout.GetControlRect(false, 1);
            EditorGUI.DrawRect(rect, new Color(0.5f, 0.5f, 0.5f, 1));
        }

        /// <summary>
        /// Draws the vertical timeline of commits.
        /// </summary>
        private void DrawTimeline()
        {
            _scrollPosition = GUILayout.BeginScrollView(_scrollPosition);

            if (_commits.Count == 0)
            {
                GUILayout.Space(20);
                GUILayout.Label("No checkpoints found.", EditorStyles.centeredGreyMiniLabel);
            }

            for (int i = 0; i < _commits.Count; i++)
            {
                var rowRect = EditorGUILayout.BeginHorizontal();
            
                var isActive = _commits[i].Hash == _activeHash;

                // Draw Selection Highlight
                if (_selectedIndex == i)
                {
                    EditorGUI.DrawRect(rowRect, new Color(0.15f, 0.4f, 0.75f, 0.4f)); // Unity Blue-ish
                }
                else if (isActive)
                {
                    EditorGUI.DrawRect(rowRect, new Color(0.2f, 0.6f, 0.3f, 0.2f)); // Subtle Green for active
                }

                // Timeline graphics layout calculations
                const float timelineX = 20f;
                const float rowHeight = 45f;
            
                // Set forced row height
                GUILayout.Space(rowHeight); 

                if (Event.current.type == EventType.Repaint)
                {
                    // Draw vertical line connecting nodes
                    var lineRect = new Rect(timelineX, rowRect.y, 2, rowHeight);
                    // If it's the first or last, adjust the line so it doesn't extend past the node
                    if (i == 0) lineRect = new Rect(timelineX, rowRect.y + rowHeight / 2, 2, rowHeight / 2);
                    if (i == _commits.Count - 1) lineRect = new Rect(timelineX, rowRect.y, 2, rowHeight / 2);
                    if (_commits.Count == 1) lineRect.height = 0; // No line needed for single commit
                
                    EditorGUI.DrawRect(lineRect, Color.gray);

                    // Draw the timeline node (circle/square)
                    var nodeRect = new Rect(timelineX - 4, rowRect.y + (rowHeight / 2) - 5, 10, 10);
                
                    var nodeColor = Color.white;
                    if (isActive) nodeColor = Color.green;
                    else if (_selectedIndex == i) nodeColor = Color.cyan;
                
                    EditorGUI.DrawRect(nodeRect, nodeColor);
                }

                // Commit Information Text
                GUILayout.Space(35); // Push text past the timeline graphics
                GUILayout.BeginVertical();
                GUILayout.Space(5);
            
                GUILayout.BeginHorizontal();
                GUILayout.Label(_commits[i].Message, EditorStyles.boldLabel);
                if (isActive)
                {
                    var activeStyle = new GUIStyle(EditorStyles.boldLabel);
                    activeStyle.normal.textColor = new Color(0.2f, 0.8f, 0.2f); // Bright green text
                    GUILayout.Label("CURRENT", activeStyle, GUILayout.Width(70));
                }
                GUILayout.EndHorizontal();

                GUILayout.Label(_commits[i].Time + "  [" + _commits[i].Hash.Substring(0, 7) + "]", EditorStyles.miniLabel);
                GUILayout.EndVertical();

                EditorGUILayout.EndHorizontal();

                // Handle Mouse Click for Selection
                if (Event.current.type == EventType.MouseDown && rowRect.Contains(Event.current.mousePosition))
                {
                    _selectedIndex = i;
                
                    // Handle Double Click to Restore
                    if (Event.current.clickCount == 2 && !_isProcessing)
                    {
                        RestoreCheckpointAsync(_commits[i]);
                    }
                
                    Repaint();
                }
            }

            GUILayout.EndScrollView();
        }

        /// <summary>
        /// Draws the bottom bar containing the "Restore" button.
        /// </summary>
        private void DrawBottomBar()
        {
            // Separator
            var rect = EditorGUILayout.GetControlRect(false, 1);
            EditorGUI.DrawRect(rect, new Color(0.5f, 0.5f, 0.5f, 1));
        
            GUILayout.Space(10);

            // The restore button is only active if a valid index is selected and we are not currently processing a git command
            EditorGUI.BeginDisabledGroup(_selectedIndex < 0 || _selectedIndex >= _commits.Count || _isProcessing);
        
            if (GUILayout.Button("Restore", GUILayout.Height(35)))
            {
                RestoreCheckpointAsync(_commits[_selectedIndex]);
            }
        
            EditorGUI.EndDisabledGroup();
            GUILayout.Space(10);
        }

        /// <summary>
        /// Commits all current changes in the Unity project asynchronously to prevent UI freezes.
        /// </summary>
        private async void CreateCheckpointAsync()
        {
            if (_isProcessing) return;
            _isProcessing = true;

            var timestamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");

            try
            {
                // Ensure .gitignore exists before adding files
                EnsureGitIgnoreExists();

                EditorUtility.DisplayProgressBar("Unity Rewinder", "Preparing timeline...", 0.1f);
            
                // If we previously restored an old checkpoint, we are in a 'detached HEAD' state.
                // We want to preserve the divergent timeline, so we branch the old 'main' before overwriting it.
                try {
                    var headRef = (await Task.Run(() => RunGitCommand("rev-parse --abbrev-ref HEAD"))).Trim();
                
                    if (headRef != "main")
                    {
                        try 
                        {
                            string branchTs = DateTime.Now.ToString("yyyyMMdd_HHmmss");
                            await Task.Run(() => RunGitCommand($"branch archive/main_{branchTs} main"));
                        } 
                        catch { } // main might not exist or we might not have divergent history
                    
                        await Task.Run(() => RunGitCommand("checkout -B main"));
                    }
                } 
                catch { }

                EditorUtility.DisplayProgressBar("Unity Rewinder", "Staging files... (This might take a while for large changes)", 0.3f);
            
                // Add all files - Run in background thread to avoid freezing Unity Editor
                await Task.Run(() => RunGitCommand("add ."));
            
                EditorUtility.DisplayProgressBar("Unity Rewinder", "Committing changes...", 0.7f);
            
                // Commit - Run in background thread
                string result = await Task.Run(() => RunGitCommand($"commit -m \"{timestamp}\""));
            
                // Ensure the branch is explicitly named main (in case this was the very first commit and it defaulted to master)
                try { await Task.Run(() => RunGitCommand("branch -M main")); } catch { }
            
                if (result.Contains("nothing to commit"))
                {
                    EditorUtility.DisplayDialog("Notice", "No changes detected. Nothing to checkpoint.", "OK");
                }
            
                RefreshTimeline();
            
                // Auto-select the newly created checkpoint (top of the list)
                _selectedIndex = 0; 
            }
            catch (Exception ex)
            {
                UnityEngine.Debug.LogError("Failed to create checkpoint: " + ex.Message);
                EditorUtility.DisplayDialog("Error", "Failed to create checkpoint. Check the console for details.", "OK");
            }
            finally
            {
                EditorUtility.ClearProgressBar();
                _isProcessing = false;
                Repaint();
            }
        }

        /// <summary>
        /// Checks out the specified commit asynchronously after prompting the user.
        /// </summary>
        private async void RestoreCheckpointAsync(CommitData commit)
        {
            var confirm = EditorUtility.DisplayDialog(
                "Restore Checkpoint",
                $"Are you sure you want to restore to:\n'{commit.Message}'?\n\nWARNING: Any uncommitted changes in your project will be lost!",
                "Yes, Restore",
                "Cancel"
            );

            if (confirm)
            {
                if (_isProcessing) return;
                _isProcessing = true;

                try
                {
                    EditorUtility.DisplayProgressBar("Unity Rewinder", "Cleaning up uncommitted changes...", 0.2f);
                
                    // Discard any uncommitted changes first to prevent checkout conflicts
                    await Task.Run(() => RunGitCommand("reset --hard HEAD"));
                    await Task.Run(() => RunGitCommand("clean -fd"));
                
                    EditorUtility.DisplayProgressBar("Unity Rewinder", $"Restoring checkpoint {commit.Hash.Substring(0,7)}...", 0.6f);
                
                    // Checkout the specific commit
                    await Task.Run(() => RunGitCommand($"checkout {commit.Hash}"));
                
                    EditorUtility.DisplayProgressBar("Unity Rewinder", "Refreshing Asset Database...", 0.9f);
                
                    // Refresh Unity's AssetDatabase so the editor reflects the restored files
                    AssetDatabase.Refresh();
                
                    RefreshTimeline();
                    EditorUtility.DisplayDialog("Success", "Checkpoint restored successfully.", "OK");
                }
                catch (Exception ex)
                {
                    UnityEngine.Debug.LogError("Failed to restore checkpoint: " + ex.Message);
                    EditorUtility.DisplayDialog("Error", "Failed to restore checkpoint. Check the console for details.", "OK");
                }
                finally
                {
                    EditorUtility.ClearProgressBar();
                    _isProcessing = false;
                    Repaint();
                }
            }
        }

        /// <summary>
        /// Retrieves the commit history from the main branch and updates the list.
        /// </summary>
        private void RefreshTimeline()
        {
            _gitError = "";
        
            try
            {
                // Check if git is initialized
                string isInsideWorkTree = RunGitCommand("rev-parse --is-inside-work-tree");
                if (!isInsideWorkTree.Contains("true"))
                {
                    _isGitInitialized = false;
                    return;
                }
            
                _isGitInitialized = true;
            }
            catch
            {
                _isGitInitialized = false;
                return;
            }

            try
            {
                // Get the current active commit hash to highlight it
                try { _activeHash = RunGitCommand("rev-parse HEAD").Trim(); }
                catch { _activeHash = ""; }

                _commits.Clear();
                _selectedIndex = -1;

                // Fetch commits from all branches so divergent ones remain visible. 
                // Format: Hash|Subject|RelativeTime
                string logOutput = "";
                try { logOutput = RunGitCommand("--no-pager log --all --date-order --pretty=format:\"%H|%s|%ar\" -n 100"); }
                catch {
                    try { logOutput = RunGitCommand("--no-pager log HEAD --pretty=format:\"%H|%s|%ar\" -n 100"); }
                    catch { } // Leave empty
                }

                if (string.IsNullOrWhiteSpace(logOutput)) return;

                string[] lines = logOutput.Split(new[] { '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries);
            
                foreach (string line in lines)
                {
                    string[] parts = line.Split('|');
                    if (parts.Length >= 3)
                    {
                        _commits.Add(new CommitData
                        {
                            Hash = parts[0],
                            Message = parts[1],
                            Time = parts[2]
                        });
                    }
                }
            }
            catch (Exception ex)
            {
                _gitError = "Failed to load timeline: " + ex.Message;
                UnityEngine.Debug.LogWarning("Unity Rewinder: " + _gitError);
            }
        }

        /// <summary>
        /// Helper method to execute a local Git process and return its output.
        /// </summary>
        private string RunGitCommand(string arguments)
        {
            ProcessStartInfo startInfo = new ProcessStartInfo
            {
                FileName = "git",
                Arguments = arguments,
                WorkingDirectory = _workingDirectory,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            using (Process process = new Process())
            {
                process.StartInfo = startInfo;

                StringBuilder output = new StringBuilder();
                StringBuilder error = new StringBuilder();

                // Read output asynchronously to prevent deadlocks when the buffer fills up
                process.OutputDataReceived += (sender, e) => { if (e.Data != null) output.AppendLine(e.Data); };
                process.ErrorDataReceived += (sender, e) => { if (e.Data != null) error.AppendLine(e.Data); };

                process.Start();

                // Begin async reading
                process.BeginOutputReadLine();
                process.BeginErrorReadLine();

                process.WaitForExit();

                if (process.ExitCode != 0)
                {
                    throw new Exception($"Git Command Failed ({arguments}):\n{error}");
                }

                return output.ToString();
            }
        }
    }
}